### ISSUE TITLE
Finish all in the demo checklist

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#1121]
Focus on what is in (can be tweaked or improved later).

Playlists (Worlds):
- [x] First, introductory but replayable playlist
- [x] Action-oriented second playlist, showing Deathmatch
- [x] Peace-oriented second playlist, showing Diamondsnatch
- [x] REMOVED Playlist that replays unlocked minigames at random (to support variety and replayability)
- [x] Playlist that teases future minigames without unlocking them (and marks the end of the demo)

Minigames:
- [x] Diamondsnatch
- [x] Diamond Dive
- [x] Deathmatch
- [x] Diamond Warfare
- [x] Take the Crown
- [x] Claim the Banner
- [x] Rocket the Crown
- [x] Homesick Invaders
- [x] Ark of Memory
- [x] Diamond Minefield

Preview minigames:
- [x] Annexxion
- [x] Slam-A-Gon
- [x] Guard the Bridge
- [x] Undertakers
- [x] Winter Diamondsnatch

CPU:
- [x] Diamondsnatch
- [x] Diamond Dive
- [x] Deathmatch
- [x] Diamond Warfare
- [x] Take the Crown
- [x] Claim the Banner
- [x] Rocket the Crown
- [x] Homesick Invaders
- [x] Ark of Memory
- [x] Diamond Minefield
- [x] Annexxion
- [x] Slam-A-Gon
- [x] REMOVED Guard the Bridge
- [x] Undertakers
- [x] Winter Diamondsnatch

Misc:
- [x] Proper credits scene
